#debug: true
logging:
  level:
    "[com.ubiqube.etsi.mano.telemetry.jms.TracingMessagingMessageListenerAdapter]": INFO
    "[com.ubiqube.etsi.mano.mon.core.service.ExpirityJmsTemplate]": INFO
    com:
      ubiqube:
        etsi: DEBUG
    org:
      hibernate:
        SQL: INFO
      openstack4j: INFO
      springframework:
        boot:
          autoconfigure:
            logging:
              ConditionEvaluationReportLoggingListener: WARN
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
  elastic:
    metrics:
      export:
        auto-create-index: true
        host: http://mano-es:9200
        index: mano-metrics-mon
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure: 
        include: '*'
  info:
    git:
      mode: full
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: mano-mon
  artemis:
    mode: native
    broker-url: tcp://mano-artemis:61616
    user: artemis
    password: simetraehcapa
  boot:
    admin:
      client:
        username: admin
        password: admin
        url:
        - http://mano-admin:8081
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://mano-db:5432/mano_mon
    username: mano_mon
    password: mano
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    properties:
      hibernate:
        "[enable_lazy_load_no_trans]": true
  output:
    ansi:
      enabled: always


